// <auto-generated />
using System;
using BancoCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoCore.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    [Migration("20260922022119_NuevaBaseDtos")]
    partial class NuevaBaseDtos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BancoCore.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cuentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Moneda = "PEN",
                            NumeroCuenta = "PE-001-987654",
                            Saldo = 2500.00m,
                            Titular = "Rodrigo"
                        },
                        new
                        {
                            Id = 2,
                            Moneda = "PEN",
                            NumeroCuenta = "PE-002-123456",
                            Saldo = 1500.00m,
                            Titular = "Maria"
                        });
                });

            modelBuilder.Entity("BancoCore.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCuentaDestino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCuentaOrigen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transaccion");
                });
#pragma warning restore 612, 618
        }
    }
}
